export default {
  topheader:{
    lng:'English',
    home:"Accueil",
    title:"Carte interactive des émissions cumulatives des navires dans la mer des Salish",
    stitle:"EEMS",
    about:"À propos",
    disclaimer:"Clause de non-responsabilité",
    contact:"Contactez"
  },
  card:{
    info:'Info',
    timeline:"Chronologie",
    vessel:"Navire",
    emissions:"Emissions",
    references:"Référence(s)",
    shippingroutes:"Routes de navigation",
  },  
  legend:{
    title:"Légende",
    projectStatus:"État du projet",
    exportType:"Type de terminal",
    sea:"Frontière de la mer des Salish",
    vesselRoutes:"Routes des navires",
    existing:"Nouvellement existant",
    proposed:"Proposé",
    notspecified:"Non spécifié",
    inbound:"Entrant",
    outbound:"Sortant",
    emissions:"Carte thermique des émissions",
    harbour:"Port\nQuai",
    anchorage:"Mouillage",
    existingterminals:"Existants",    
  },
  select:{
    placeholder:"Choisissez un projet "
  },
  table:{
    nodata:"Ancun projet selectioné",
    vesselclass:"Classe de navire",
    movement:"Mouvement de voyage",
    link:"*Données basées sur OAIÉM 2018",
  },  
  tooltip:{
    hideExisting:"Cacher les terminaux existants",
    showExisting:"Afficher les terminaux existants",    
    changeemission:"xxxxx",
    showheatmap:"Afficher la carte termique",
    hideheatmap:"Cacher la carte termique",
    showhoveremission:"Afficher les valeurs en survol",
    hidehoveremission:"Cacher les valuers en survol",
    showAllRoutes:"Afficher les routes des navires",
    hideAllRoutes:"Cacher les routes des navires",
  },  
  sclass:{
  "Canadian O/D-Only":"Canadien O/D",
  "Includes non Canadian O/D": "Comprend non Canadien O/D",
  "Main Engine":"Moteur Principale",
  "Boiler":"Chaudière",
  "Auxiliary Engines":"Moteur Auxiliaire",
  "Underway":"En Cours",
  "Berthed":"Accosté",
  "Anchored":"Ancré",
  "(None)":"(Aucun)",
  "<All U.S. Coast Guard Vessels>":"<Tous Navires Garde Côtière Americains>",
  "U.S. Coast Guard":"Garde côtière américaine",
  "<All Barges>":"<Toutes les Barges>",
  "Barge":"Barge",
  "Barge Chips":"Barge à Copeaux",
  "Barge Derrick":"Barge de forage",
  "Barge Log":"Barge à billot",
  "Barge Rail/Trailer":"Barge Trains/Remorques",
  "Barge General":"Barge Général",
  "Barge Bulk Cargo":"Barge vraquier",
  "Don't use":"Ne pas utiliser",
  "Barge Chemical":"Barge produits Chimique",
  "Logs Raft Section":"section de billots flottants",
  "Barge Oil Drilling Rig":"Barge d'équipement de forage pétrolier",
  "Barge Oil/Petroleum":"Barge produit Petrolier",
  "Barge Towed":"Barge en remorque",
  "Barge Self-Propelled":"Barge autopropulsée",
  "Barge Miscellaneous":"Barge multi-usage",
  "<All Coast Guard Vessels>":"<Tous Navires Garde Côtière>",
  "Coast Guard":"Navires Garde Côtière",
  "Coast Guard Cable":"Garde-côte cablier",
  "Coast Guard Supply":"Garde côte approvisionnement",
  "Coast Guard Hovercraft":"Garde-côte Aéroglisseur",
  "Coast Guard Icebreaker":"Garde côte brise-glace",
  "Coast Guard Lifeboat":"Garde côte Survie",
  "Coast Guard Patrol":"Garde côtière patrouilleur",
  "Coast Guard Rescue":"Garde côte sauvetage",
  "Coast Guard Scientific":"Garde côte scientifique",
  "Coast Guard Tender":"Garde côtière ravitaillement",
  "<All DFO Vessels>":"<Tous Navires DFO >",
  "DFO Fishing Surveillance Vessel":"MPO Navire de Surveillance des peches",
  "<All Excursion Vessels>":"<Tous Navires Excursion>",
  "Excursion Passenger":"Excursion Passager",
  "<All Fishing Vessels>":"<Tous Navires de pêche>",
  "Fishing":"Navires de pêche",
  "Crab Boat":"Crabier",
  "Dragger (Scallop, Clam, etc.)":"Dragueur (pétoncle, etc.)",
  "Factory Ship":"Navire usine",
  "Other Fishing VSL (Open Boat)":"Autres pêches (bateau ouvert)",
  "Lobster Boat":"Pêche au homard",
  "Longliner":"Peche de haute mer (filet)",
  "Seiner":"Chalutier à senne",
  "Groundfish Boat (Open Boat)":"Poisson de fond (bat. ouvert)",
  "Fishery Patrol":"Patrouilleur de pêche",
  "Troller":"Chalutier côtier",
  "Shrimp Boat":"Crevettier",
  "Trawler":"Chalutier de haute mer",
  "Gillnetter":"Chalutier enrouleur",
  "Fishing Vessel":"Navire de pêche",
  "<All Tugs>":"<Tous Remorqueurs>",
  "Tug Fire":"Remorqueur - Bateau à incendie",
  "Tug Harbour":"Remorqueur de port",
  "Tug Ocean":"Remorqueur de mer",
  "Tug Supply":"Remorqueur - Approvisionnement",
  "Tug":"Remorqueur",
  "Tugs Workboat":"Remorqueur - Bateau de travail",
  "<All Innav Test Vessels>":"<Tous Navires Innav Test>",
  "INNAV Test Vessel":"INNAV Navire Test",
  "Landing Craft":"Péniche de débarquement",
  "<All Merchant Vessels>":"<Tous Navires Marchands>",
  "Merchant Auto":"Marchand Vehicules",
  "Merchant Bulk":"Marchand vraquier",
  "Merchant Container":"Marchand conteneurs",
  "Merchant Cement":"Marchand ciment",
  "Merchant Ferry":"Marchand traversier",
  "Merchant General":"Cargo général",
  "Merchant RO/RO":"Marchand RO/RO",
  "Merchant Livestock":"Marchand Bétail Vivant",
  "Merchant Lash":"Marchand à attaches",
  "Merchant (Dry)":"Marchand (marchandises sèches)",
  "Merchant Ore":"Marchand minerais",
  "Merchant Passenger":"Marchand passagers",
  "Merchant Rail/Trailer Ferry":"Marchand Traversier Trains Remorques",
  "Merchant Reefer":"Marchand Réfrigéré",
  "Merchant Coastal":"Marchand caboteur",
  "Cruise":"Croisière",
  "<All Other type Vessels>":"<Tous Autre type de navire>",
  "<Other type>":"<Autre Type>",
  "<All Special Vessels>":"<Tous Navires Spéciaux>",
  "Special Purpose Crane ship":"Fonct. spéc. navire-grue",
  "Dredge":"Drague",
  "Special Purpose Cable VSL":"Fonctions spéciales cablier",
  "Special Purpose Diving":"Fonctions spéciales plongée",
  "Special Purpose Hydrofoil":"Fonctions spéciales hydroptère",
  "Special Purpose Hovercraft":"Fonct. spéc. Aéroglisseur",
  "Special Purpose Pipe-Layer":"Fonctions spéciales canalisations",
  "Special Purpose Training VSI":"Fonct. spéc. navire-école",
  "Special Purpose Pilot Boat":"Fonctions Spéciales Bateau Pilote",
  "Special Purpose Research VSL":"Fonctions spéciales recherches",
  "Special Purpose":"Fonctions spéciales",
  "Special Purpose Tour":"Fonctions spéciales tours",
  "Special Purpose Supply VSL":"Fonct. spéc. approvisionnement",
  "Special Purpose Survey Ship":"Fonctions spéciales Recherches hydrographiques",
  "<All Tankers>":"<Tous Navires Citernes>",
  "Merchant Crude":"Citerne pétrole brut",
  "Merchant Gasoline":"Citerne gazoline",
  "Merchant Chemical":"Citerne produits chimiques",
  "Merchant Molasses":"Citerne mélasses",
  "Merchant Ore/Bulk/Oil":"Citerne/minerais/vrac/pétrole",
  "Merchant Chemical/Oil Products Tanker":"Citerne Produits Chimique/Pétrole",
  "Merchant Liquified Gas":"Citerne gaz liquéfié",
  "Merchant Super Tanker":"Citerne 'Super tanker'",
  "Merchant (Tanker)":"Citerne Marchand",
  "Merchant ULCC":"Citerne ULCC",
  "Merchant VLCC":"Citerne VLCC",
  "Merchant Water":"Citerne eau",
  "Merchant Other":"Citerne inconnu",
  "Tanker":"Citerne",
  "Unknown":"Inconnu",
  "<All War Vessels>":"<Tous Navires de Guerre>",
  "War":"Navires de Guerre",
  "Warship - General":"Navire de guerre - général",
  "Warship Surface":"Navire de guerre - surface",
  "Warship Training":"Navire de guerre - Formation",
  "Warship Undersea":"Navire de guerre sous-marin",
  "<All Pleasure Crafts>":"<Tous Plaisanciers>",
  "Pleasure Craft":"Plaisancier",
  "Yacht Power":"Yacht motorisé",
  "Yacht Sails":"Yacht voilier",
  "Yacht - Pleasure Crafts":"Yacht - plaisanciers"
    },

};
